---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: acme-crt
  namespace: python-demo
spec:
  secretName: python-crt-secret
  dnsNames:
  - pythonapp.cxcto.cisco.com
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: istio.banzaicloud.io/v1beta1
kind: MeshGateway
metadata:
  name: python-ingress
  namespace: python-demo
spec:
  maxReplicas: 1
  minReplicas: 1
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: http2
    port: 8002
    protocol: TCP
    targetPort: 8002
  serviceType: LoadBalancer
  type: ingress

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: python-gateway
  namespace: python-demo
spec:
  selector:
    gateway-name: python-ingress
    gateway-type: ingress
  servers:
  - port:
      number: 8001
      name: http
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: python-crt-secret
    hosts:
    - "pythonapp.cxcto.cisco.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: python-server
  namespace: python-demo
spec:
  hosts:
  - "pythonapp.cxcto.cisco.com"
  gateways:
  - python-gateway
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: python-app.python-demo.svc.cluster.local
