apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  params:
    - name: flags
      default: --
    - name: argocd-version
      default: v2.0.0
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap 
      - secretRef:
          name: argocd-env-secret  # MANUAL
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:$(params.argocd-version)
      securityContext:
        runAsUser: 0
      script: |
        echo "35.225.46.52         argocd.example.com" > /etc/hosts
        argocd login $ARGOCD_SERVER --grpc-web --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
        argocd app sync $ARGOCD_APPLICATION_NAME --grpc-web --server $ARGOCD_SERVER --insecure
        argocd app wait $ARGOCD_APPLICATION_NAME --health --grpc-web --server $ARGOCD_SERVER --insecure

