---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: trigger-gateway
  namespace: python-demo
spec:
  selector:
    gateway-name: python-ingress
    gateway-type: ingress
  servers:
  - port:
      number: 8002
      name: http
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: python-crt-secret
    hosts:
    - "pythonapp.cxcto.cisco.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: trigger-server
  namespace: python-demo
spec:
  hosts:
  - "pythonapp.cxcto.cisco.com"
  gateways:
  - trigger-gateway
  http:
  - route:
    - destination:
        host: el-tekton-argocd-example-build-el.tekton-pipelines.svc.cluster.local
