apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: triggers-gateway
  namespace: tekton-pipelines
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: triggers-app
  namespace: tekton-pipelines
spec:
  hosts:
  - "*"
  gateways:
  - triggers-gateway
  http:
  - route:
    - destination:
        host: el-tekton-argocd-example-build-el
