
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildpacks-app-image 
  namespace: tekton-pipelines
spec:
  type: image
  params:
    - name: url
      value: 842793852320.dkr.ecr.us-east-1.amazonaws.com/pythonapp #This defines the name of output image
