
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildpacks-app-image 
  namespace: tekton-pipelines
spec:
  type: image
  params:
    - name: url
      value: baojingbo/tekton-test:19.0 #This defines the name of output image
