apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-task-sync-and-wait
spec:
  params:
    - name: application-name
      description: name of the application to sync
    - name: revision
      description: the revision to sync to
      default: HEAD
    - name: flags
      default: --
    - name: argocd-version
      default: v2.0.0
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap 
      - secretRef:
          name: argocd-env-secret  # MANUAL
  steps:
    - name: argocd-app-sync  
      image: argoproj/argocd:$(params.argocd-version)
      securityContext:
        runAsUser: 0
      script: |
        argocd login $ARGOCD_SERVER --grpc-web --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
        argocd app sync "$(params.application-name)" --revision "$(params.revision)" --grpc-web --server $ARGOCD_SERVER --insecure
        argocd app wait "$(params.application-name)" --health --grpc-web --server $ARGOCD_SERVER --insecure

